trigger: 
  - main

resources:
  repositories:
    - repository: 'pc-nrfconnect-shared'
      type: github
      name: NordicSemiconductor/pc-nrfconnect-shared
      ref: build-app-pipeline
extends:
  template: build-app.yml@pc-nrfconnect-shared
   