trigger:
- master
- release/*
pool:
  vmImage: 'Ubuntu-20.04'
variables:
- group: wayland
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14
- script: |
    set -o errexit -o pipefail
    echo "token=$(WAYLAND_GITHUB_PRIVATE_TOKEN)" > ~/.prebuild-installrc
    npm i -g npm@6
    npm config set //npm.nordicsemi.no/:_authToken $(WAYLAND_NPM_TOKEN_INTERNAL)
    npm ci
    npm run lint
    npm run test
    npm run build
    npm pack
  displayName: 'Build and pack'
- bash: |
    set -o errexit -o pipefail
    cp *.tgz "$(Build.ArtifactStagingDirectory)"
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: 'Copy artifacts'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    publishLocation: 'pipeline'
  displayName: 'Publish artifacts to artifact storage'
