site_name: Cellular Monitor app documentation
site_url:
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: custom-blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: custom-blue-dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  # logo: assets/logo.png
  # favicon: assets/logo.png
  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow


extra_css:
  - stylesheets/style.css

copyright:
  Copyright &copy; 2023

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - macros
  - search


extra:
  test: This is a test abbreviation snippet
  app_name: Cellular Monitor app

nav:
  - Home: index.md
  - Installing the Cellular Monitor app: installing.md
  - Minimum requirements and limitations: requirements.md
  - Overview and user interface: overview.md
  - Preparing the device for modem trace: preparing.md
  - Capturing a modem trace: capturing.md
  - Viewing a modem trace in the Cellular Monitor app: viewing.md
  - Using Wireshark: wireshark.md
  - Loading modem traces for play back: loading.md
  - Viewing RTT modem traces: viewing_rtt.md
  - Memfault and modem trace in production: memfault_in_production.md
  - Managing modem credentials: managing_credentials.md
  - Troubleshooting: troubleshooting.md
  - Revision history: revision_history.md
